### ISSUE TITLE
Example Code has errors

### ISSUE THREAD

**Issue by DarkyOMG** [Musicted/pyghthouse#2]
In line 99 of pyghthouse/pyghthouse/ph.py it states that img[3,9] = [255, 127, 0] would turn some window orange. 
The indices are wrong. It has to be img[3][9] or something equivalent.
Also in Line 97 it should be "not" and not "npt"

**Comment by Musicted** [comment]
You're right - that's numpy indexing. Gonna fix. Thanks!
